export default JobDetailss = [
  {
    status: "OK",
    request_id: "11c882d7-8096-4a8d-b815-0d85e275744d",
    parameters: {
      job_id: "PDQ2_wDIQKl9Y6mrAAAAAA==",
      extended_publisher_details: false,
    },
    data: [
      {
        employer_name: "Truckup",
        employer_logo: null,
        employer_website: null,
        employer_company_type: null,
        job_publisher: "LinkedIn Nigeria",
        job_id: "PDQ2_wDIQKl9Y6mrAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Senior React Native Developer",
        job_apply_link:
          "https://ng.linkedin.com/jobs/view/senior-react-native-developer-at-truckup-3762633716",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.6117,
        job_description:
          "Company Description\n\nTruckup is a peer-to-peer platform connecting semi-truck drivers in need of breakdown repair with mobile mechanics, in real-real time — think Uber, but for semi-truck drivers & mechanics.\n\nRole Description\n\nTruckup is hiring a Senior React Native Developer who is proficient in building mobile applications. This individual must have a strong technical background when it comes to iOS & android applications and must also be attentive to details when building out UIs that match design specifications.\n\nThis individual must possess strong skills in building complex, pixel-perfect React Native user interfaces with significant use of animation.\n\nGeneral Requirements\n• You have good/great English (written & spoken)\n• You'll work full-time, 40 or more hours per week\n• You're looking for a long-term position 3+ years\n• You'll participate in a daily 15 minute google meet stand-up at 9am CST\n• 100% remote\n\nQualifications\n• 5+ years of React Native\n• 3+ years TypeScript\n• Native device APIs, especially location tracking\n• Map libraries (ie. MapBox & Google Maps).\n• CI/CD, Github Actions, Fastlane\n• Device storage and data persistence\n• iOS build processes & app store connect\n• android build process & google play store\n• State management & rendering (useState, redux, tanstack query, etc.)\n• Forms & complex form components (ie. autocomplete, dropdowns, etc.)\n• React Hook Forms\n• Restful APIs, async & fetching\n• Reusable component architecture & patterns\n• Design systems & design tokens\n• Storybook & testing\n• Git & Github\n\nAs a team member of Truckup you'll be working with a small team, including the Founder & CEO. You'll have the full autonomy to implement technologies you love and develop exciting new features.\n\nPlease reply with your resume and any other information that may be better help us make a decision — a link to your website or portfolio is always helpful.\n\nWe look forward to hearing from you!\n\nCaleb Markovich\n\nFounder & CEO",
        job_is_remote: true,
        job_posted_at_timestamp: 1700276704,
        job_posted_at_datetime_utc: "2023-11-18T03:05:04.000Z",
        job_city: "Lagos",
        job_state: "LA",
        job_country: "NG",
        job_latitude: 6.5243793,
        job_longitude: 3.3792057,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&q=PDQ2_wDIQKl9Y6mrAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=PDQ2_wDIQKl9Y6mrAAAAAA%3D%3D&htidocid=PDQ2_wDIQKl9Y6mrAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2024-05-16T03:04:23.000Z",
        job_offer_expiration_timestamp: 1715828663,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: null,
          experience_mentioned: false,
          experience_preferred: false,
        },
        job_required_skills: [
          "Mapbox",
          "React Hooks",
          "React Native",
          "React.js",
          "TypeScript",
          "Redux.js",
          "JavaScript",
          "Async",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: true,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {},
        job_job_title: "Senior",
        job_posting_language: "en",
        job_onet_soc: "15113200",
        job_onet_job_zone: "4",
        estimated_salaries: [],
        apply_options: [
          {
            publisher: "LinkedIn Nigeria",
            apply_link:
              "https://ng.linkedin.com/jobs/view/senior-react-native-developer-at-truckup-3762633716",
            is_direct: false,
          },
        ],
        employer_reviews: [],
      },
    ],
  },
];
